### PR TITLE
Allow large thresholds

### PR DESCRIPTION
**Pull request by iver56**
Motivation: float32 audio may have extreme loudness (values outside [-1, 1]) in the middle of an audio data augmentation pipeline

### CODE REVIEW

**Comment by pzelasko** [comment]
Fair enough :)

**Comment by pzelasko** [comment]
BTW if you're planning to contribute more stuff, LMK, so I'll wait a bit with releasing to PyPI

**Comment by iver56** [comment]
I'm not planning more stuff at the moment. I just created this PR, have a look if you're interested: https://github.com/iver56/audiomentations/pull/214

I might update the audiomentations code (2 TODOs in there) if/when I see a new cylimiter release 🤓

**Comment by iver56** [comment]
Especially the cylimiter Windows support would be great to have in place before I release a new audiomentations version

**Comment by pzelasko** [comment]
Cool, I'll make a release then. I remember testing it with numpy inputs, I'm not sure if I did it with torch -- I expect it to work out of the box, but if you run into sth, just let me know.

**Pull request merged**
